"""Deterministic data for the W-series manual PPT E2E sample.

All hosts, users, tokens, orders, and responses are fictional and sanitized.
The library identifiers and names mirror the W-series records in Otter's
vulnerability knowledge database.
"""

from __future__ import annotations

from typing import Iterator


FINDINGS: tuple[dict, ...] = (
    {
        "key": "w05-sqli",
        "library_id": "W-05",
        "library_name": "SQL 인젝션",
        "target_id": "WEB-02",
        "title": "[W-05] 감사 로그 검색 SQL 인젝션",
        "severity": "Critical",
        "status": "Confirmed",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
        "url": "https://admin.northstar.test/api/audit/search",
        "method": "GET",
        "parameter": "query",
        "role": "Support operator",
        "tester": "Red Team · 이서준",
        "discovered_at": "2026-07-03",
        "summary": "감사 로그 검색어가 SQL WHERE 절에 직접 결합되어 데이터베이스 표현식이 실행됩니다.",
        "impact": "지원 운영자 권한만으로 관리자 계정과 감사 데이터가 노출·변조될 수 있고 데이터베이스 서비스 중단으로 확대될 수 있습니다.",
        "remediation": "검색 조건 전체를 바인드 변수로 전환하고 검색 전용 읽기 계정을 분리하며 데이터베이스 오류를 외부 응답에서 제거하십시오.",
        "root_cause": "query 값을 문자열 보간하여 SQL 조건절을 만들고 애플리케이션 DB 계정에도 불필요한 쓰기 권한이 부여되어 있습니다.",
        "analysis": "격리된 Staging DB에서 읽기 전용 UNION 표현식의 결과로 실행 계정과 스키마 식별자가 반환됐으며 추가 데이터 추출 없이 중단했습니다.",
        "preconditions": "승인된 지원 운영자 계정과 가상 데이터만 포함한 Staging DB를 사용하며 데이터 변경 쿼리는 실행하지 않습니다.",
        "steps": (
            {
                "slug": "w05-01-auth-context",
                "title": "검색 권한과 테스트 경계 확인",
                "action": "지원 운영자 계정으로 로그인하고 audit:read 권한과 검색 대상이 가상 감사 데이터로 제한됐는지 확인합니다.",
                "expected": "운영자에게 감사 검색 권한만 부여되어야 합니다.",
                "observed": "support.lee 계정에 audit:read만 부여된 것을 확인했습니다.",
                "mode": "identity",
                "endpoint": "Access context / support.lee",
                "request": "role=support_operator\nscope=audit:read\nenvironment=staging",
                "response": "database_admin=false\nwrite_scope=false\napproved_test_data=true",
            },
            {
                "slug": "w05-02-baseline",
                "title": "정상 검색 응답 기준선 확보",
                "action": "password-reset 키워드로 정상 검색을 실행해 결과 수, 상태 코드, 쿼리 시간을 기록합니다.",
                "expected": "정상 키워드는 200 OK로 반환되어야 합니다.",
                "observed": "12건이 142ms 안에 정상 반환됐습니다.",
                "mode": "api",
                "endpoint": "GET /api/audit/search?query=password-reset",
                "request": "Authorization: Bearer support-token\nquery=password-reset\nlimit=20",
                "response": "HTTP/1.1 200 OK\ncount=12\nqueryTime=38ms",
            },
            {
                "slug": "w05-03-union-request",
                "title": "읽기 전용 UNION 표현식 전송",
                "action": "query에 current_user만 반환하는 비파괴 UNION 표현식을 넣고 동일 요청을 한 번 재전송합니다.",
                "expected": "입력은 데이터로 처리되거나 400 응답으로 거부되어야 합니다.",
                "observed": "표현식이 SQL 구문으로 해석되어 200 OK가 반환됐습니다.",
                "mode": "api",
                "endpoint": "GET /api/audit/search",
                "request": "query=x' UNION SELECT current_user,null--\nlimit=20",
                "response": "HTTP/1.1 200 OK\nqueryAccepted=true\nrows=1",
                # One logical procedure can own multiple evidence items.  The
                # planner must choose the two-image single-step layout instead
                # of splitting this into two procedures.
                "extra_evidence": (
                    {
                        "slug": "w05-03-query-trace",
                        "title": "동일 요청의 데이터베이스 실행 추적",
                        "mode": "logs",
                        "endpoint": "Query trace · req-8a21d7",
                        "request": "requestId=req-8a21d7\nparameter=query\nmutation=disabled",
                        "response": "statementType=UNION SELECT\nrows=1\ntransaction=read-only",
                        "expected": "외부 입력은 SQL 실행 계획을 바꾸지 않아야 합니다.",
                        "observed": "동일 요청 ID의 읽기 전용 추적에서 UNION SELECT 실행이 확인됐습니다.",
                    },
                ),
            },
            {
                "slug": "w05-04-stop-boundary",
                "title": "DB 실행 결과 확인 후 안전 중단",
                "action": "응답에 DB 실행 계정과 스키마 식별자가 포함됐는지 확인하고 민감 레코드 조회나 쓰기 검증 없이 즉시 종료합니다.",
                "expected": "DB 내부 식별자는 응답에 포함되지 않아야 합니다.",
                "observed": "northstar_admin_app과 public.audit_event가 반환되어 취약점을 확정했습니다.",
                "mode": "logs",
                "endpoint": "Query trace · req-8a21d7",
                "request": "expression=current_user\nmutation=disabled\nstopOnProof=true",
                "response": "dbUser=northstar_admin_app\nschema=public.audit_event\nwriteAttempts=0",
            },
        ),
        "result": {
            "slug": "w05-result",
            "title": "SQL 표현식 실행과 DB 컨텍스트 노출 확인",
            "caption": "파라미터화되지 않은 검색 조건으로 DB 실행 계정과 내부 스키마가 반환된 최종 판정 화면",
            "mode": "result",
            "endpoint": "W-05 · Final result",
            "request": "Affected parameter: query\nReproduction: 1/1\nData mutation: none",
            "response": "Status: Confirmed\nSeverity: Critical\nDB context exposed",
        },
    },
    {
        "key": "w08-xss",
        "library_id": "W-08",
        "library_name": "크로스사이트 스크립팅",
        "target_id": "WEB-01",
        "title": "[W-08] 공지사항 저장형 크로스사이트 스크립팅",
        "severity": "High",
        "status": "Confirmed",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:H/A:N",
        "url": "https://portal.northstar.test/notices/{noticeId}",
        "method": "POST",
        "parameter": "content",
        "role": "Content editor",
        "tester": "Red Team · 박지아",
        "discovered_at": "2026-07-04",
        "summary": "공지 본문에 저장된 이벤트 핸들러가 관리자 브라우저에서 HTML로 렌더링되어 스크립트가 실행됩니다.",
        "impact": "공격자는 공지 검수자의 세션 컨텍스트에서 비인가 작업을 수행하거나 화면의 민감정보에 접근할 수 있습니다.",
        "remediation": "HTML 허용목록 기반 정화와 출력 문맥별 인코딩을 적용하고 nonce 기반 CSP를 심층 방어로 구성하십시오.",
        "root_cause": "편집 API가 이벤트 속성을 보존하고 뷰어가 공지 본문을 innerHTML로 직접 삽입합니다.",
        "analysis": "외부 통신과 쿠키 접근이 없는 로컬 테스트 플래그만 사용해 별도 검수자 세션에서 실행 여부를 확인했습니다.",
        "preconditions": "가상 편집자·검수자 계정과 외부 통신이 차단된 격리 브라우저를 사용합니다.",
        "steps": (
            {
                "slug": "w08-01-baseline",
                "title": "정상 공지 본문 출력 확인",
                "action": "일반 텍스트와 허용된 강조 서식으로 공지를 저장해 정상 출력 기준선을 확보합니다.",
                "expected": "허용된 콘텐츠만 동일하게 표시되어야 합니다.",
                "observed": "정상 공지가 검수자 화면에 텍스트로 표시됐습니다.",
                "mode": "browser",
                "endpoint": "Notice preview · NOTICE-2407",
                "request": "title=7월 시스템 점검 안내\ncontent=<strong>점검 시간</strong> 02:00",
                "response": "renderMode=safe-html\nscriptExecuted=false\nstatus=Published",
            },
            {
                "slug": "w08-02-payload-save",
                "title": "비통신 이벤트 속성 저장",
                "action": "네트워크 요청이나 쿠키 접근 없이 window 테스트 플래그만 설정하는 img onerror 값을 공지 본문에 저장합니다.",
                "expected": "이벤트 속성이 제거되거나 문자로 인코딩되어야 합니다.",
                "observed": "sanitized=false 상태로 이벤트 속성이 원문 저장됐습니다.",
                "mode": "api",
                "endpoint": "POST /api/notices",
                "request": "content=<img src=x onerror=window.__XSS_TEST__=true>\nexternalUrl=none",
                "response": "HTTP/1.1 201 Created\nsanitized=false\nnoticeId=NOTICE-2411",
            },
            {
                "slug": "w08-03-reviewer-render",
                "title": "별도 검수자 세션에서 실행 확인",
                "action": "검수자 계정으로 저장된 공지를 열고 DOM 플래그와 CSP 적용 상태를 확인한 뒤 브라우저 프로필을 폐기합니다.",
                "expected": "저장된 값이 실행 가능한 DOM으로 생성되지 않아야 합니다.",
                "observed": "검수자 세션에서 __XSS_TEST__ 값이 true로 변경되고 CSP 헤더가 없었습니다.",
                "mode": "browser",
                "endpoint": "Reviewer browser · NOTICE-2411",
                "request": "viewer=reviewer.kim\nprofile=isolated\nnetwork=blocked",
                "response": "window.__XSS_TEST__=true\nCSP=(missing)\ncookieRead=false",
            },
        ),
        "result": {
            "slug": "w08-result",
            "title": "검수자 브라우저에서 저장 스크립트 실행",
            "caption": "외부 통신 없는 플래그가 별도 사용자 세션에서 실행된 저장형 XSS 최종 판정 화면",
            "mode": "result",
            "endpoint": "W-08 · Final result",
            "request": "Stored payload: NOTICE-2411\nVictim role: reviewer\nNetwork egress: blocked",
            "response": "Status: Confirmed\nSeverity: High\nDOM flag executed",
        },
    },
    {
        "key": "w11-redirect",
        "library_id": "W-11",
        "library_name": "URL 리다이렉션",
        "target_id": "WEB-01",
        "title": "[W-11] 로그인 완료 URL 외부 리다이렉션",
        "severity": "Medium",
        "status": "Accepted",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
        "url": "https://portal.northstar.test/login?returnUrl={url}",
        "method": "GET",
        "parameter": "returnUrl",
        "role": "Unauthenticated",
        "tester": "Red Team · 최윤호",
        "discovered_at": "2026-07-05",
        "summary": "로그인 완료 후 returnUrl 값의 외부 호스트를 검증하지 않아 신뢰 도메인을 이용한 피싱 이동이 가능합니다.",
        "impact": "공격자는 정상 로그인 화면에서 외부 피싱 페이지로 사용자를 이동시켜 자격정보 재입력이나 OAuth 코드 노출을 유도할 수 있습니다.",
        "remediation": "서버 측 목적지 키 또는 내부 상대경로만 허용하고 불가피한 외부 이동에는 정규화된 호스트 허용목록과 사용자 경고를 적용하십시오.",
        "root_cause": "인증 성공 핸들러가 returnUrl을 URL 파싱과 허용목록 확인 없이 Location 헤더에 사용합니다.",
        "analysis": "가상 외부 도메인을 목적지로 지정한 단일 요청에서 302 Location 헤더가 그대로 생성됨을 확인했습니다.",
        "preconditions": "외부 통신이 없는 가상 피싱 도메인과 일회용 테스트 계정을 사용합니다.",
        "steps": (
            {
                "slug": "w11-01-external-location",
                "title": "외부 returnUrl 처리 확인",
                "action": "로그인 URL의 returnUrl에 가상 외부 도메인을 넣고 인증 성공 후 Location 헤더와 최종 호스트를 한 번 확인합니다.",
                "expected": "외부 목적지는 거부되거나 안전한 내부 기본 페이지로 변경되어야 합니다.",
                "observed": "302 Location에 https://login-check.example.test가 그대로 포함됐습니다.",
                "mode": "browser",
                "endpoint": "GET /login?returnUrl=https://login-check.example.test",
                "request": "account=test.redirect\nreturnUrl=https://login-check.example.test\nrequestCount=1",
                "response": "HTTP/1.1 302 Found\nLocation: https://login-check.example.test\nallowlistCheck=false",
            },
        ),
        "result": {
            "slug": "w11-result",
            "title": "외부 목적지가 Location 헤더에 그대로 반영됨",
            "caption": "로그인 성공 후 외부 도메인으로 이동 가능한 URL 리다이렉션 최종 판정 화면",
            "mode": "result",
            "endpoint": "W-11 · Final result",
            "request": "Parameter: returnUrl\nExternal host: controlled test domain\nRequests: 1",
            "response": "Status: Accepted\nSeverity: Medium\nRisk owner: Digital Channel",
        },
    },
    {
        "key": "w16-authorization",
        "library_id": "W-16",
        "library_name": "불충분한 인가",
        "target_id": "WEB-02",
        "title": "[W-16] 파트너 정산 승인 권한 우회",
        "severity": "Critical",
        "status": "Confirmed",
        "category": "Access Control",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
        "url": "https://admin.northstar.test/api/settlements/approve",
        "method": "POST",
        "parameter": "settlementId",
        "role": "Partner analyst",
        "tester": "Red Team · 김민서",
        "discovered_at": "2026-07-07",
        "summary": "파트너 조회 역할이 관리자 전용 정산 승인 API를 직접 호출해 다른 조직의 지급 상태를 변경할 수 있습니다.",
        "impact": "공격자는 수직·수평 권한을 동시에 우회해 타 조직 정산을 승인하거나 지급 흐름을 조작할 수 있습니다.",
        "remediation": "모든 정산 API에 역할, 조직, 객체 상태를 함께 검증하는 중앙 정책을 기본 거부 방식으로 적용하고 승인 작업에 재인증을 추가하십시오.",
        "root_cause": "화면 메뉴만 역할로 숨기고 API는 로그인 여부만 확인하며 settlement.tenantId와 토큰 tenant 클레임을 비교하지 않습니다.",
        "analysis": "가상 파트너 계정으로 타 조직의 Draft 정산을 Approved로 변경했고 감사 로그에도 partner_analyst 주체가 기록됐습니다.",
        "preconditions": "조직이 다른 두 가상 파트너와 승인 전 정산 레코드, 지급이 비활성화된 Staging 환경을 사용합니다.",
        "steps": (
            {
                "slug": "w16-01-role-baseline",
                "title": "파트너 역할 권한 기준선 확인",
                "action": "partner_analyst 계정의 토큰 역할과 조직 범위, 화면에서 허용된 조회 메뉴를 기록합니다.",
                "expected": "정산 조회만 가능하고 승인 권한은 없어야 합니다.",
                "observed": "UI에는 조회 메뉴만 표시되고 settlement:approve 권한은 없었습니다.",
                "mode": "identity",
                "endpoint": "Session inspector · partner.choi",
                "request": "role=partner_analyst\ntenant=TENANT-A\nscope=settlement:read",
                "response": "ui.approveVisible=false\nsettlement:approve=false\nlogin=true",
            },
            {
                "slug": "w16-02-own-record",
                "title": "자기 조직 정산 조회 기준선",
                "action": "TENANT-A 소유 정산 ST-A-104를 조회해 정상 객체와 상태 전이 전 값을 기록합니다.",
                "expected": "자기 조직의 읽기 권한은 허용되어야 합니다.",
                "observed": "ST-A-104가 200 OK와 Draft 상태로 반환됐습니다.",
                "mode": "admin",
                "endpoint": "GET /api/settlements/ST-A-104",
                "request": "tenant=TENANT-A\nactor=partner.choi\naction=read",
                "response": "HTTP/1.1 200 OK\nowner=TENANT-A\nstatus=Draft",
            },
            {
                "slug": "w16-03-cross-tenant-read",
                "title": "타 조직 객체 접근 조건 교차 확인",
                "action": "동일한 partner_analyst 토큰을 유지한 상태에서 경로의 settlementId만 TENANT-B 소유 ST-B-778로 변경하고, 응답 상태·객체 tenantId·토큰 tenant 클레임을 함께 대조하여 서버 측 조직 경계가 적용되는지 확인합니다.",
                "expected": "조직이 다른 객체는 403 또는 404로 차단되어야 합니다.",
                "observed": "TENANT-B 정산의 금액과 상태가 200 OK로 반환됐습니다.",
                "mode": "api",
                "endpoint": "GET /api/settlements/ST-B-778",
                "request": "token.tenant=TENANT-A\npath.id=ST-B-778\naction=read",
                "response": "HTTP/1.1 200 OK\nobject.tenant=TENANT-B\namount=₩84,200,000",
            },
            {
                "slug": "w16-04-approve-request",
                "title": "관리자 승인 API 직접 호출",
                "action": "화면에 없는 approve 엔드포인트를 동일 토큰으로 직접 호출하고 권한 판단 결과를 확인합니다.",
                "expected": "settlement:approve 권한이 없어 403이 반환되어야 합니다.",
                "observed": "승인 요청이 200 OK로 처리됐습니다.",
                "mode": "api",
                "endpoint": "POST /api/settlements/ST-B-778/approve",
                "request": "actor=partner.choi\nrole=partner_analyst\nreason=manual-e2e-test",
                "response": "HTTP/1.1 200 OK\nprevious=Draft\ncurrent=Approved",
            },
            {
                "slug": "w16-05-state-change",
                "title": "타 조직 정산 상태 변경 확인",
                "action": "승인 전후 객체를 비교해 TENANT-B 정산 상태와 승인자 필드가 실제로 변경됐는지 확인합니다.",
                "expected": "권한 없는 요청으로 데이터 상태가 변경되지 않아야 합니다.",
                "observed": "status=Approved, approvedBy=partner.choi로 저장됐습니다.",
                "mode": "admin",
                "endpoint": "Settlement diff · ST-B-778",
                "request": "before.status=Draft\nbefore.approvedBy=null",
                "response": "after.status=Approved\nafter.approvedBy=partner.choi\nobject.tenant=TENANT-B",
            },
            {
                "slug": "w16-06-audit-log",
                "title": "감사 로그 주체와 권한 불일치 확인",
                "action": "승인 이벤트의 actor, role, tenant, policyDecision 필드를 확인해 우회 경로를 기록합니다.",
                "expected": "거부 이벤트가 남고 상태 변경 이벤트는 없어야 합니다.",
                "observed": "policyDecision=login_only로 승인 성공 이벤트가 기록됐습니다.",
                "mode": "logs",
                "endpoint": "Audit event · evt-91db2",
                "request": "event=SETTLEMENT_APPROVED\nactor=partner.choi\nrole=partner_analyst",
                "response": "tenant=TENANT-A\nresourceTenant=TENANT-B\npolicyDecision=login_only",
            },
            {
                "slug": "w16-07-stop-restore",
                "title": "지급 비활성 상태 확인 후 원복",
                "action": "실제 지급 작업이 비활성화된 것을 재확인하고 테스트 정산을 Draft로 원복한 뒤 추가 객체 접근 없이 종료합니다.",
                "expected": "테스트 데이터만 원복되고 외부 지급은 발생하지 않아야 합니다.",
                "observed": "paymentDispatch=false를 확인하고 ST-B-778을 Draft로 복구했습니다.",
                "mode": "logs",
                "endpoint": "Safety boundary · ST-B-778",
                "request": "paymentDispatch=false\nrollbackRequested=true\nadditionalObjects=0",
                "response": "rollback=completed\nfinalStatus=Draft\nexternalPayment=none",
            },
        ),
        "result": {
            "slug": "w16-result",
            "title": "파트너 계정으로 타 조직 관리자 승인 수행",
            "caption": "역할·조직 권한검사 누락으로 타 조직 정산 상태가 변경된 최종 판정 화면",
            "mode": "result",
            "endpoint": "W-16 · Final result",
            "request": "Actor: partner_analyst\nActor tenant: TENANT-A\nResource tenant: TENANT-B",
            "response": "Status: Confirmed\nSeverity: Critical\nVertical + horizontal bypass",
        },
    },
    {
        "key": "w24-errors",
        "library_id": "W-24",
        "library_name": "에러 처리 결함",
        "target_id": "WEB-03",
        "title": "[W-24] 결제 API 상세 예외정보 노출",
        "severity": "Medium",
        "status": "Confirmed",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
        "url": "https://api.northstar.test/v2/payments/confirm",
        "method": "POST",
        "parameter": "paymentKey",
        "role": "Unauthenticated",
        "tester": "Red Team · 정하린",
        "discovered_at": "2026-07-09",
        "summary": "잘못된 결제 키를 처리할 때 스택 추적, 내부 파일 경로, 라이브러리 버전과 데이터베이스 호스트가 응답에 노출됩니다.",
        "impact": "공격자는 내부 아키텍처와 구성요소 버전을 수집해 알려진 취약점과 후속 공격 경로를 정교화할 수 있습니다.",
        "remediation": "외부 오류는 일반 메시지와 추적 ID만 반환하고 상세 예외는 민감정보를 제거해 접근 통제된 중앙 로그에 기록하십시오.",
        "root_cause": "운영 API의 debugErrors 플래그가 활성화되어 전역 예외 처리기가 exception.toString과 stackTrace를 응답 body에 직렬화합니다.",
        "analysis": "서로 다른 오류 입력에서 동일한 상세 정보가 반복 노출됐으며 정상 결제나 대량 요청 없이 오류 처리 경로만 검증했습니다.",
        "preconditions": "실제 결제와 연결되지 않은 가상 paymentKey를 사용하고 최대 3회 요청 후 중단합니다.",
        "steps": (
            {
                "slug": "w24-01-normal-error",
                "title": "정상 오류 응답 기준선 확인",
                "action": "존재하지 않는 결제 키로 한 번 요청해 일반 오류 코드와 추적 ID가 제공되는지 확인합니다.",
                "expected": "일반 메시지와 추적 ID만 반환되어야 합니다.",
                "observed": "첫 응답부터 exceptionClass 필드가 포함됐습니다.",
                "mode": "api",
                "endpoint": "POST /v2/payments/confirm",
                "request": "paymentKey=pay_test_missing\norderId=ORDER-E2E-1001",
                "response": "HTTP/1.1 500\nerror=PaymentLookupException\ntraceId=tr-2048",
            },
            {
                "slug": "w24-02-stack-trace",
                "title": "스택 추적 노출 범위 확인",
                "action": "응답의 stackTrace에 내부 패키지명과 소스 파일 경로가 포함됐는지 확인합니다.",
                "expected": "스택 추적은 외부 응답에 포함되지 않아야 합니다.",
                "observed": "PaymentService.java:284와 배포 경로가 노출됐습니다.",
                "mode": "logs",
                "endpoint": "Exception response · tr-2048",
                "request": "Accept=application/json\nX-Debug=(not set)",
                "response": "class=PaymentLookupException\nfile=/srv/payment/PaymentService.java:284\nstackFrames=17",
            },
            {
                "slug": "w24-03-db-host",
                "title": "내부 데이터베이스 연결정보 노출 확인",
                "action": "원인 예외 체인에서 내부 DB 호스트, 포트, 스키마 식별자가 반환되는지 확인합니다.",
                "expected": "인프라 연결정보는 외부에 노출되지 않아야 합니다.",
                "observed": "pg-payments.internal:5432와 payments_v2가 포함됐습니다.",
                "mode": "logs",
                "endpoint": "Root cause chain · tr-2048",
                "request": "causeDepth=3\nredactionPolicy=expected",
                "response": "host=pg-payments.internal\nport=5432\nschema=payments_v2",
            },
            {
                "slug": "w24-04-version-banner",
                "title": "프레임워크 버전 정보 확인",
                "action": "응답 헤더와 오류 템플릿에서 서버·프레임워크 버전이 함께 노출되는지 확인합니다.",
                "expected": "구성요소의 상세 버전은 제거되어야 합니다.",
                "observed": "Spring Boot 3.1.1과 Netty 4.1.92가 표시됐습니다.",
                "mode": "api",
                "endpoint": "Error headers · tr-2048",
                "request": "method=POST\ncontentType=application/json",
                "response": "X-Powered-By=Spring Boot 3.1.1\nServer=Netty/4.1.92\nHTTP=500",
            },
            {
                "slug": "w24-05-consistency",
                "title": "오류 유형별 응답 일관성 비교",
                "action": "누락 키와 형식 오류의 응답 구조를 비교해 상세 예외 노출이 특정 경로가 아닌 공통 처리기의 문제인지 확인합니다.",
                "expected": "모든 오류는 동일한 안전 형식으로 정규화되어야 합니다.",
                "observed": "두 오류 모두 stackTrace와 causeChain을 반환해 공통 핸들러 결함을 확인했습니다.",
                "mode": "logs",
                "endpoint": "Error normalization comparison",
                "request": "caseA=missing-key\ncaseB=malformed-key\nrequests=2",
                "response": "caseA.detailFields=6\ncaseB.detailFields=6\ncommonHandler=DebugErrorAdvice",
            },
        ),
        "result": {
            "slug": "w24-result",
            "title": "결제 오류 응답에서 내부 구성정보가 반복 노출됨",
            "caption": "스택 추적·파일 경로·DB 호스트·프레임워크 버전이 함께 노출된 최종 판정 화면",
            "mode": "result",
            "endpoint": "W-24 · Final result",
            "request": "Error cases: 2\nPayment execution: none\nSensitive records: none",
            "response": "Status: Confirmed\nSeverity: Medium\nInternal topology disclosed",
        },
    },
    {
        "key": "w28-business-logic",
        "library_id": "W-28",
        "library_name": "비즈니스 로직 취약점",
        "target_id": "WEB-01",
        "title": "[W-28] 환불 요청 재전송으로 중복 적립금 지급",
        "severity": "High",
        "status": "Resolved",
        "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
        "url": "https://portal.northstar.test/api/refunds/complete",
        "method": "POST",
        "parameter": "Idempotency-Key",
        "role": "Authenticated customer",
        "tester": "Red Team · 오유진",
        "discovered_at": "2026-07-10",
        "summary": "동일 환불 완료 요청을 재전송하면 멱등성 검증 없이 적립금 지급 이벤트가 반복 생성됩니다.",
        "impact": "공격자는 한 건의 환불로 적립금을 중복 수령해 직접적인 재무 손실과 정산 불일치를 유발할 수 있습니다.",
        "remediation": "환불 상태 전이와 적립금 지급을 단일 트랜잭션으로 묶고 주문 단위 멱등성 키와 유일 제약을 적용하십시오.",
        "root_cause": "환불 상태 확인과 적립금 이벤트 발행 사이에 원자성이 없고 Idempotency-Key가 저장·검증되지 않습니다.",
        "analysis": "조치 전 동일 요청 2회에 대해 두 개의 CREDIT 이벤트가 생성됐고 조치 후에는 두 번째 요청이 기존 결과를 재사용했습니다.",
        "preconditions": "잔액이 없는 가상 고객, 환불 가능 가상 주문, 외부 정산이 비활성화된 Staging 환경을 사용합니다.",
        "steps": (
            {
                "slug": "w28-01-first-refund",
                "title": "첫 환불 완료 요청과 잔액 확인",
                "action": "고정 Idempotency-Key로 환불 완료 요청을 보내 적립금 이벤트와 고객 잔액을 기록합니다.",
                "expected": "환불 1건에 CREDIT 이벤트 1건만 생성되어야 합니다.",
                "observed": "CREDIT-701이 생성되고 잔액이 50,000원 증가했습니다.",
                "mode": "admin",
                "endpoint": "POST /api/refunds/RF-901/complete",
                "request": "Idempotency-Key=refund-rf901-e2e\namount=50000\nrequestNo=1",
                "response": "HTTP/1.1 200 OK\ncreditEvent=CREDIT-701\nbalance=50000",
            },
            {
                "slug": "w28-02-replay",
                "title": "동일 요청 재전송 결과 비교",
                "action": "동일한 환불 ID와 Idempotency-Key로 한 번 재전송해 신규 지급 이벤트와 잔액 변화를 확인합니다.",
                "expected": "기존 결과를 재사용하고 추가 적립금은 지급되지 않아야 합니다.",
                "observed": "CREDIT-702가 새로 생성되고 잔액이 100,000원으로 증가했습니다.",
                "mode": "admin",
                "endpoint": "Replay · RF-901",
                "request": "Idempotency-Key=refund-rf901-e2e\namount=50000\nrequestNo=2",
                "response": "HTTP/1.1 200 OK\ncreditEvent=CREDIT-702\nbalance=100000",
            },
        ),
        "result": {
            "slug": "w28-result",
            "title": "동일 환불 요청으로 적립금이 두 번 지급됨",
            "caption": "같은 멱등성 키에서 CREDIT 이벤트 2건과 잔액 중복 증가가 확인된 최종 판정 화면",
            "mode": "result",
            "endpoint": "W-28 · Original result",
            "request": "Refund: RF-901\nRequests: 2 identical\nExpected credits: 1",
            "response": "Original status: Confirmed\nCredit events: 2\nBalance delta: ₩100,000",
        },
        "retest": {
            "slug": "w28-retest",
            "tested_at": "2026-07-16",
            "tester": "Red Team · 오유진",
            "result": "Passed",
            "remediation_summary": "환불 상태 전이와 적립금 이벤트를 단일 트랜잭션으로 묶고 refundId+Idempotency-Key 유일 제약을 배포했습니다.",
            "verification_details": "동일 요청을 재전송했을 때 기존 CREDIT-801 결과가 반환되고 잔액과 이벤트 수가 증가하지 않았습니다.",
            "notes": "동시 요청 5개에서도 CREDIT 이벤트는 한 건만 생성됐습니다.",
            "title": "멱등성 조치 후 중복 지급 차단 확인",
            "caption": "동일 요청 재전송과 동시 요청에서 기존 결과가 재사용된 재진단 화면",
            "mode": "retest",
            "endpoint": "Retest · RF-RET-2026",
            "request": "Identical requests=2\nConcurrent requests=5\nIdempotency-Key=refund-retest-2026",
            "response": "Result=Passed\nCredit events=1\nBalance delta=₩50,000",
        },
    },
)


def iter_step_evidence_specs(step: dict) -> Iterator[dict]:
    """Yield the screenshots attached to one procedure."""

    if step.get("evidence_mode") != "none":
        yield step
    for extra in step.get("extra_evidence", ()):
        yield {**step, **extra}


def iter_evidence_specs() -> Iterator[dict]:
    """Yield step, result, and retest evidence with finding context."""

    for finding in FINDINGS:
        for index, step in enumerate(finding["steps"], start=1):
            for evidence in iter_step_evidence_specs(step):
                yield {
                    **evidence,
                    "kind": "procedure",
                    "library_id": finding["library_id"],
                    "library_name": finding["library_name"],
                    "finding_title": finding["title"],
                    "severity": finding["severity"],
                    "status": finding["status"],
                    "step_number": index,
                    "step_count": len(finding["steps"]),
                    "actor": finding["role"],
                }
        yield {
            **finding["result"],
            "kind": "result",
            "library_id": finding["library_id"],
            "library_name": finding["library_name"],
            "finding_title": finding["title"],
            "severity": finding["severity"],
            "status": finding["status"],
            "step_number": len(finding["steps"]),
            "step_count": len(finding["steps"]),
            "actor": finding["role"],
            "expected": "최종 결과 증적은 취약점마다 정확히 한 장이어야 합니다.",
            "observed": finding["result"]["caption"],
        }
        if finding.get("retest"):
            yield {
                **finding["retest"],
                "kind": "retest",
                "library_id": finding["library_id"],
                "library_name": finding["library_name"],
                "finding_title": finding["title"],
                "severity": finding["severity"],
                "status": finding["status"],
                "step_number": 1,
                "step_count": 1,
                "actor": finding["role"],
                "expected": "동일 요청은 기존 결과를 재사용해야 합니다.",
                "observed": finding["retest"]["verification_details"],
            }


EVIDENCE_COUNT = sum(1 for _ in iter_evidence_specs())
PROCEDURE_EVIDENCE_COUNT = sum(
    sum(1 for _ in iter_step_evidence_specs(step))
    for item in FINDINGS
    for step in item["steps"]
)
RESULT_EVIDENCE_COUNT = len(FINDINGS)
